### ISSUE TITLE
renderer.js:22 TypeError: Cannot read property 'address' of undefined

### ISSUE THREAD

**Issue by mrgroen** [ahwelgemoed/rg-mx#2]
I am trying to get this running.
But when i use this on my Windows 10 machine in Vmware Fusion I get the following message in the console of the windows app.

`renderer.js:22 TypeError: Cannot read property 'address' of undefined`

**Comment by ahwelgemoed** [comment]
Hey - I have downloaded a Free version of VMWare Fusion and will try and replicate the issue. 
I will get back to you in the next couple days. 

Thanks!

**Comment by ahwelgemoed** [comment]
I have fixed this issue in V1.0.2 - Well I hope its fixed. I have implemented a beter way to get the windows IP. Hopefully this resolves the issue.  🚀
